language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get update
  - sudo apt-get install screen -y
# command to run tests
script:
  - git clone https://github.com/unauna1803/travershin.git
  - pip install -r requirements.txt
  - cd travershin
  - chmod +x app.py
  - python3 app.py || python app.py
  - pytest
